plugins:
  musicbrainz_enabled:
    default: true
    client: true

  musicbrainz_load_caa_images:
    default: true

  musicbrainz_load_wikimedia_images:
    default: true

  musicbrainz_load_other_images:
    default: true

  musicbrainz_show_wikipedia_link:
    default: true

  musicbrainz_genre_limit:
    default: 5
